//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFIRM.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssetsView
    {
        public int Id { get; set; }
        public string NodeName { get; set; }
        public string NodeValue { get; set; }
        public Nullable<int> ParentId { get; set; }
        public Nullable<int> NodeTypeId { get; set; }
        public Nullable<int> SubNodeTypeId { get; set; }
        public Nullable<int> UserGroupId { get; set; }
        public Nullable<int> RelativeId { get; set; }
    }
}
