//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFIRM.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EFIRMDBEntities : DbContext
    {
        public EFIRMDBEntities()
            : base("name=EFIRMDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AlarmPointFetchDateTime> AlarmPointFetchDateTimes { get; set; }
        public virtual DbSet<AnalogValueStatu> AnalogValueStatus { get; set; }
        public virtual DbSet<AssetsView> AssetsViews { get; set; }
        public virtual DbSet<DigitalValueStatu> DigitalValueStatus { get; set; }
        public virtual DbSet<From_Unit> From_Unit { get; set; }
        public virtual DbSet<LocationMaster> LocationMasters { get; set; }
        public virtual DbSet<NodeType> NodeTypes { get; set; }
        public virtual DbSet<Point> Points { get; set; }
        public virtual DbSet<PointValue_Digital> PointValue_Digital { get; set; }
        public virtual DbSet<PPMWorkOrderService> PPMWorkOrderServices { get; set; }
        public virtual DbSet<PPMWorkOrderServiceSoft> PPMWorkOrderServiceSofts { get; set; }
        public virtual DbSet<RunhoursAnalogPointFetchDateTime> RunhoursAnalogPointFetchDateTimes { get; set; }
        public virtual DbSet<RunhoursDigitalPointFetchDateTime> RunhoursDigitalPointFetchDateTimes { get; set; }
        public virtual DbSet<Sel_Point> Sel_Point { get; set; }
        public virtual DbSet<tbl_AlarmSummary> tbl_AlarmSummary { get; set; }
        public virtual DbSet<tbl_Devices> tbl_Devices { get; set; }
        public virtual DbSet<tbl_EscalationMatrixNotificationStatus> tbl_EscalationMatrixNotificationStatus { get; set; }
        public virtual DbSet<tbl_ExceptionLogItems> tbl_ExceptionLogItems { get; set; }
        public virtual DbSet<tbl_LogParameter> tbl_LogParameter { get; set; }
        public virtual DbSet<tbl_newUpdatealarm> tbl_newUpdatealarm { get; set; }
        public virtual DbSet<tbl_ObjectList> tbl_ObjectList { get; set; }
        public virtual DbSet<tbl_ObjectType> tbl_ObjectType { get; set; }
        public virtual DbSet<tbl_PointValue_Digital> tbl_PointValue_Digital { get; set; }
        public virtual DbSet<tbl_RoomBookingMailStatus> tbl_RoomBookingMailStatus { get; set; }
        public virtual DbSet<tbl_RunHrsOnOffTime> tbl_RunHrsOnOffTime { get; set; }
        public virtual DbSet<tbl_TaskDetailforAssetMaintenance> tbl_TaskDetailforAssetMaintenance { get; set; }
        public virtual DbSet<tbl_TaskDetails> tbl_TaskDetails { get; set; }
        public virtual DbSet<tbl_TotalizationHistory> tbl_TotalizationHistory { get; set; }
        public virtual DbSet<tbl_TotalizationLastFetchStatus> tbl_TotalizationLastFetchStatus { get; set; }
        public virtual DbSet<tbl_TotalizationStatus> tbl_TotalizationStatus { get; set; }
        public virtual DbSet<tbl_UnitOfMeasure> tbl_UnitOfMeasure { get; set; }
        public virtual DbSet<tblAccountBalance> tblAccountBalances { get; set; }
        public virtual DbSet<tblAccountHead> tblAccountHeads { get; set; }
        public virtual DbSet<tblAccountSubHead> tblAccountSubHeads { get; set; }
        public virtual DbSet<tblActualValueDigital> tblActualValueDigitals { get; set; }
        public virtual DbSet<tblActualValueFloat> tblActualValueFloats { get; set; }
        public virtual DbSet<tblAddWorkForceSkill> tblAddWorkForceSkills { get; set; }
        public virtual DbSet<tblAlarmGenerationLastCheckTimeStamp> tblAlarmGenerationLastCheckTimeStamps { get; set; }
        public virtual DbSet<tblAlarmType> tblAlarmTypes { get; set; }
        public virtual DbSet<tblAnalogAlarm> tblAnalogAlarms { get; set; }
        public virtual DbSet<tblApproverManagersList> tblApproverManagersLists { get; set; }
        public virtual DbSet<tblArea> tblAreas { get; set; }
        public virtual DbSet<tblAreaUnit> tblAreaUnits { get; set; }
        public virtual DbSet<tblAssetComponent> tblAssetComponents { get; set; }
        public virtual DbSet<tblAssetComponentType> tblAssetComponentTypes { get; set; }
        public virtual DbSet<tblAssetGroup> tblAssetGroups { get; set; }
        public virtual DbSet<tblAssetListReportTemplate> tblAssetListReportTemplates { get; set; }
        public virtual DbSet<tblAsset> tblAssets { get; set; }
        public virtual DbSet<tblAssetsFrequency> tblAssetsFrequencies { get; set; }
        public virtual DbSet<tblAssetsRunHour> tblAssetsRunHours { get; set; }
        public virtual DbSet<TblAssetToMaintenanceTeamMapping> TblAssetToMaintenanceTeamMappings { get; set; }
        public virtual DbSet<tblAssetType> tblAssetTypes { get; set; }
        public virtual DbSet<tblAssetTypeFrequency> tblAssetTypeFrequencies { get; set; }
        public virtual DbSet<tblAssetTypeNQualificationLevel> tblAssetTypeNQualificationLevels { get; set; }
        public virtual DbSet<tblAttachedResourcesRoomWise> tblAttachedResourcesRoomWises { get; set; }
        public virtual DbSet<tblAuditReport> tblAuditReports { get; set; }
        public virtual DbSet<tblBimonthlyLogger> tblBimonthlyLoggers { get; set; }
        public virtual DbSet<tblBookingRate> tblBookingRates { get; set; }
        public virtual DbSet<tblBuilding> tblBuildings { get; set; }
        public virtual DbSet<tblBuildingHoliday> tblBuildingHolidays { get; set; }
        public virtual DbSet<tblBuildingWorkingSchedule> tblBuildingWorkingSchedules { get; set; }
        public virtual DbSet<tblCategory> tblCategories { get; set; }
        public virtual DbSet<tblCategory_HelpDesk> tblCategory_HelpDesk { get; set; }
        public virtual DbSet<tblCommentsSRP> tblCommentsSRPs { get; set; }
        public virtual DbSet<tblComponentTypeAsset> tblComponentTypeAssets { get; set; }
        public virtual DbSet<tblCountryDetail> tblCountryDetails { get; set; }
        public virtual DbSet<tblCourse> tblCourses { get; set; }
        public virtual DbSet<tblCurrencyMaster> tblCurrencyMasters { get; set; }
        public virtual DbSet<tblCustomerFeedback> tblCustomerFeedbacks { get; set; }
        public virtual DbSet<tblCustomerFeedbackUserRoleMapping> tblCustomerFeedbackUserRoleMappings { get; set; }
        public virtual DbSet<tblDailyLogger> tblDailyLoggers { get; set; }
        public virtual DbSet<tblDatabaseConnectionString> tblDatabaseConnectionStrings { get; set; }
        public virtual DbSet<TblDefectTracking> TblDefectTrackings { get; set; }
        public virtual DbSet<tblDefineSoftservice> tblDefineSoftservices { get; set; }
        public virtual DbSet<tblDesignation> tblDesignations { get; set; }
        public virtual DbSet<tblDocument> tblDocuments { get; set; }
        public virtual DbSet<tblDocumentType> tblDocumentTypes { get; set; }
        public virtual DbSet<tblEmailConfiguration> tblEmailConfigurations { get; set; }
        public virtual DbSet<tblExtraAddedResourcesForBooking> tblExtraAddedResourcesForBookings { get; set; }
        public virtual DbSet<tblFacility> tblFacilities { get; set; }
        public virtual DbSet<tblFacilityHoliday> tblFacilityHolidays { get; set; }
        public virtual DbSet<tblFacilityWorkingSchedule> tblFacilityWorkingSchedules { get; set; }
        public virtual DbSet<tblFBAnnouncementMngt> tblFBAnnouncementMngts { get; set; }
        public virtual DbSet<tblFBAttachResourcesRoomWise> tblFBAttachResourcesRoomWises { get; set; }
        public virtual DbSet<tblFBBookingSlot> tblFBBookingSlots { get; set; }
        public virtual DbSet<tblFBBusinessRule> tblFBBusinessRules { get; set; }
        public virtual DbSet<tblFBInvoiceDetail> tblFBInvoiceDetails { get; set; }
        public virtual DbSet<tblFBInvoiceIdRoomBookingId> tblFBInvoiceIdRoomBookingIds { get; set; }
        public virtual DbSet<tblFBRoomDetail> tblFBRoomDetails { get; set; }
        public virtual DbSet<tblFBRoomDetailsWiseRate> tblFBRoomDetailsWiseRates { get; set; }
        public virtual DbSet<tblFiscalYear> tblFiscalYears { get; set; }
        public virtual DbSet<tblFloor> tblFloors { get; set; }
        public virtual DbSet<tblFloorHoliday> tblFloorHolidays { get; set; }
        public virtual DbSet<tblFloorWorkingSchedule> tblFloorWorkingSchedules { get; set; }
        public virtual DbSet<tblForm> tblForms { get; set; }
        public virtual DbSet<tblFrequencyType> tblFrequencyTypes { get; set; }
        public virtual DbSet<tblGLCode> tblGLCodes { get; set; }
        public virtual DbSet<tblHelpDeskBusinessRule> tblHelpDeskBusinessRules { get; set; }
        public virtual DbSet<tblHelpDeskChangeRTAsset> tblHelpDeskChangeRTAssets { get; set; }
        public virtual DbSet<tblHelpDeskChangeRTDetail> tblHelpDeskChangeRTDetails { get; set; }
        public virtual DbSet<tblHelpDeskChangeRTResource> tblHelpDeskChangeRTResources { get; set; }
        public virtual DbSet<tblHelpDeskRedirectAsset> tblHelpDeskRedirectAssets { get; set; }
        public virtual DbSet<tblHelpDeskRedirectFlow> tblHelpDeskRedirectFlows { get; set; }
        public virtual DbSet<tblHelpDeskRedirectResource> tblHelpDeskRedirectResources { get; set; }
        public virtual DbSet<tblHelpDeskTemplate> tblHelpDeskTemplates { get; set; }
        public virtual DbSet<tblHourlyLogger> tblHourlyLoggers { get; set; }
        public virtual DbSet<tblIfcTagMaster> tblIfcTagMasters { get; set; }
        public virtual DbSet<tblInventoryComponent> tblInventoryComponents { get; set; }
        public virtual DbSet<tblInventoryIssueReturn> tblInventoryIssueReturns { get; set; }
        public virtual DbSet<tblInventoryPart> tblInventoryParts { get; set; }
        public virtual DbSet<tblIssueReturnItemsList> tblIssueReturnItemsLists { get; set; }
        public virtual DbSet<tblIssueReturnItemsListComponent> tblIssueReturnItemsListComponents { get; set; }
        public virtual DbSet<tblKeyPanel> tblKeyPanels { get; set; }
        public virtual DbSet<tblKeyReturnedStatu> tblKeyReturnedStatus { get; set; }
        public virtual DbSet<tblKey> tblKeys { get; set; }
        public virtual DbSet<tblKeysInPanel> tblKeysInPanels { get; set; }
        public virtual DbSet<tblKeysIssueReturn> tblKeysIssueReturns { get; set; }
        public virtual DbSet<tblKPI> tblKPIs { get; set; }
        public virtual DbSet<tblKPI_AssetDetails> tblKPI_AssetDetails { get; set; }
        public virtual DbSet<tblLicence> tblLicences { get; set; }
        public virtual DbSet<tblLoggerHistory> tblLoggerHistories { get; set; }
        public virtual DbSet<TblMachineStateReport> TblMachineStateReports { get; set; }
        public virtual DbSet<tblMainModule> tblMainModules { get; set; }
        public virtual DbSet<tblMaintenanceActivite> tblMaintenanceActivites { get; set; }
        public virtual DbSet<tblMaintenanceActivityAsset> tblMaintenanceActivityAssets { get; set; }
        public virtual DbSet<tblMaintenanceTask> tblMaintenanceTasks { get; set; }
        public virtual DbSet<tblMaintenanceTaskActivity> tblMaintenanceTaskActivities { get; set; }
        public virtual DbSet<tblMaintenanceTeam> tblMaintenanceTeams { get; set; }
        public virtual DbSet<tblMaintenanceType> tblMaintenanceTypes { get; set; }
        public virtual DbSet<tblMakeMaster> tblMakeMasters { get; set; }
        public virtual DbSet<tblModelMaster> tblModelMasters { get; set; }
        public virtual DbSet<tblModule> tblModules { get; set; }
        public virtual DbSet<tblMonthlyLogger> tblMonthlyLoggers { get; set; }
        public virtual DbSet<tblMRCourierServiceProvider> tblMRCourierServiceProviders { get; set; }
        public virtual DbSet<tblMRMailroomInbound> tblMRMailroomInbounds { get; set; }
        public virtual DbSet<tblMRMailroomOutbound> tblMRMailroomOutbounds { get; set; }
        public virtual DbSet<tblMRModeOfDelivery> tblMRModeOfDeliveries { get; set; }
        public virtual DbSet<tblNodeDoumentView> tblNodeDoumentViews { get; set; }
        public virtual DbSet<tblNode> tblNodes { get; set; }
        public virtual DbSet<tblNotification_HelpDesk> tblNotification_HelpDesk { get; set; }
        public virtual DbSet<tblNotificationQueue> tblNotificationQueues { get; set; }
        public virtual DbSet<tblOccupant> tblOccupants { get; set; }
        public virtual DbSet<tblPart> tblParts { get; set; }
        public virtual DbSet<tblPartsAsset> tblPartsAssets { get; set; }
        public virtual DbSet<tblPartsType> tblPartsTypes { get; set; }
        public virtual DbSet<tblPayment> tblPayments { get; set; }
        public virtual DbSet<tblPlanBadget> tblPlanBadgets { get; set; }
        public virtual DbSet<tblPlusActual> tblPlusActuals { get; set; }
        public virtual DbSet<tblPMAsset> tblPMAssets { get; set; }
        public virtual DbSet<tblPMSoftService> tblPMSoftServices { get; set; }
        public virtual DbSet<tblPortfolio> tblPortfolios { get; set; }
        public virtual DbSet<tblPPMSchedule> tblPPMSchedules { get; set; }
        public virtual DbSet<tblPPMschedulesoftservice> tblPPMschedulesoftservices { get; set; }
        public virtual DbSet<tblPPMTask> tblPPMTasks { get; set; }
        public virtual DbSet<tblPredictiveType> tblPredictiveTypes { get; set; }
        public virtual DbSet<tblPrefixesMaster> tblPrefixesMasters { get; set; }
        public virtual DbSet<tblProgram> tblPrograms { get; set; }
        public virtual DbSet<tblPurchaseOrderList> tblPurchaseOrderLists { get; set; }
        public virtual DbSet<tblPurchaseRequisition> tblPurchaseRequisitions { get; set; }
        public virtual DbSet<tblQuickLink> tblQuickLinks { get; set; }
        public virtual DbSet<tblRealTimeBooking> tblRealTimeBookings { get; set; }
        public virtual DbSet<tblReortInventoryTemplate> tblReortInventoryTemplates { get; set; }
        public virtual DbSet<tblReportDataLogger> tblReportDataLoggers { get; set; }
        public virtual DbSet<tblReportPPMSchedule> tblReportPPMSchedules { get; set; }
        public virtual DbSet<tblReportShiftSchedule> tblReportShiftSchedules { get; set; }
        public virtual DbSet<tblReportSoftServicesPPM> tblReportSoftServicesPPMs { get; set; }
        public virtual DbSet<tblReportWorkForceAttacnance> tblReportWorkForceAttacnances { get; set; }
        public virtual DbSet<tblReportWorkForceList> tblReportWorkForceLists { get; set; }
        public virtual DbSet<tblRequestDescription> tblRequestDescriptions { get; set; }
        public virtual DbSet<tblRequestTypeApprover> tblRequestTypeApprovers { get; set; }
        public virtual DbSet<tblResetTotalizationRunHour> tblResetTotalizationRunHours { get; set; }
        public virtual DbSet<tblResourceMakeModel> tblResourceMakeModels { get; set; }
        public virtual DbSet<tblRoom> tblRooms { get; set; }
        public virtual DbSet<tblRoomBookingHistory> tblRoomBookingHistories { get; set; }
        public virtual DbSet<tblRoomBookingMaster> tblRoomBookingMasters { get; set; }
        public virtual DbSet<tblRoomRecurringBooking> tblRoomRecurringBookings { get; set; }
        public virtual DbSet<tblRoomType> tblRoomTypes { get; set; }
        public virtual DbSet<tblRunHour> tblRunHours { get; set; }
        public virtual DbSet<tblServiceReport> tblServiceReports { get; set; }
        public virtual DbSet<tblServiceReportComponentsUsed> tblServiceReportComponentsUseds { get; set; }
        public virtual DbSet<tblServiceReportFilePath> tblServiceReportFilePaths { get; set; }
        public virtual DbSet<tblServiceReportPart> tblServiceReportParts { get; set; }
        public virtual DbSet<tblServiceReportWorkForceTime> tblServiceReportWorkForceTimes { get; set; }
        public virtual DbSet<tblServiceRequest> tblServiceRequests { get; set; }
        public virtual DbSet<tblServiceRequestImage> tblServiceRequestImages { get; set; }
        public virtual DbSet<tblServiceRequestMappedAsset> tblServiceRequestMappedAssets { get; set; }
        public virtual DbSet<tblServiceRequestResource> tblServiceRequestResources { get; set; }
        public virtual DbSet<tblServiceRequestStatu> tblServiceRequestStatus { get; set; }
        public virtual DbSet<TblServiceState> TblServiceStates { get; set; }
        public virtual DbSet<tblServiceStateUserRoleMapping> tblServiceStateUserRoleMappings { get; set; }
        public virtual DbSet<tblServiceStatusMaster> tblServiceStatusMasters { get; set; }
        public virtual DbSet<tblServiceType> tblServiceTypes { get; set; }
        public virtual DbSet<tblSeverity> tblSeverities { get; set; }
        public virtual DbSet<tblShiftException> tblShiftExceptions { get; set; }
        public virtual DbSet<tblShiftRostering> tblShiftRosterings { get; set; }
        public virtual DbSet<tblShift> tblShifts { get; set; }
        public virtual DbSet<tblSkill> tblSkills { get; set; }
        public virtual DbSet<tblSLA> tblSLAs { get; set; }
        public virtual DbSet<tblSLACategoryType> tblSLACategoryTypes { get; set; }
        public virtual DbSet<tblSLAEscalation> tblSLAEscalations { get; set; }
        public virtual DbSet<tblSmsStatu> tblSmsStatus { get; set; }
        public virtual DbSet<tblSoftservicetoMaitenanceteamMapping> tblSoftservicetoMaitenanceteamMappings { get; set; }
        public virtual DbSet<tblStatutoryCompliance> tblStatutoryCompliances { get; set; }
        public virtual DbSet<tblStatutoryComplianceEmailStatu> tblStatutoryComplianceEmailStatus { get; set; }
        public virtual DbSet<tblStockDetail> tblStockDetails { get; set; }
        public virtual DbSet<tblStore> tblStores { get; set; }
        public virtual DbSet<tblTaskAssetmaintenance> tblTaskAssetmaintenances { get; set; }
        public virtual DbSet<tblTaskSoftservice> tblTaskSoftservices { get; set; }
        public virtual DbSet<tblTimeSheet> tblTimeSheets { get; set; }
        public virtual DbSet<tblUnit> tblUnits { get; set; }
        public virtual DbSet<tblUnitOfMeasure> tblUnitOfMeasures { get; set; }
        public virtual DbSet<tblUnitOfPartType> tblUnitOfPartTypes { get; set; }
        public virtual DbSet<tblUserLoginInfo> tblUserLoginInfoes { get; set; }
        public virtual DbSet<tblUserRole> tblUserRoles { get; set; }
        public virtual DbSet<tblUserRolesRights_Access> tblUserRolesRights_Access { get; set; }
        public virtual DbSet<tblVendorComparison> tblVendorComparisons { get; set; }
        public virtual DbSet<tblVendorComparisonMain> tblVendorComparisonMains { get; set; }
        public virtual DbSet<tblVendorMasterGeneral> tblVendorMasterGenerals { get; set; }
        public virtual DbSet<tblVendorQualificationLevelName> tblVendorQualificationLevelNames { get; set; }
        public virtual DbSet<tblVendor> tblVendors { get; set; }
        public virtual DbSet<tblVM_GateReceiptNumber> tblVM_GateReceiptNumber { get; set; }
        public virtual DbSet<tblVM_GRN_ComponentQuantity> tblVM_GRN_ComponentQuantity { get; set; }
        public virtual DbSet<tblVM_GRN_PartQuantity> tblVM_GRN_PartQuantity { get; set; }
        public virtual DbSet<tblVM_POContract> tblVM_POContract { get; set; }
        public virtual DbSet<tblVM_PurchaseRequisitionForm> tblVM_PurchaseRequisitionForm { get; set; }
        public virtual DbSet<tblVM_RFP_ForService> tblVM_RFP_ForService { get; set; }
        public virtual DbSet<tblVM_RFPforComponents> tblVM_RFPforComponents { get; set; }
        public virtual DbSet<tblVM_RFPforManpower> tblVM_RFPforManpower { get; set; }
        public virtual DbSet<tblVM_RFPforManpower_Main> tblVM_RFPforManpower_Main { get; set; }
        public virtual DbSet<tblVM_RFPforManpower_VendorSelection> tblVM_RFPforManpower_VendorSelection { get; set; }
        public virtual DbSet<tblVM_RFPforParts> tblVM_RFPforParts { get; set; }
        public virtual DbSet<tblVM_RFPforPartsComponentMain> tblVM_RFPforPartsComponentMain { get; set; }
        public virtual DbSet<tblVM_RFPforProjectWork> tblVM_RFPforProjectWork { get; set; }
        public virtual DbSet<tblVM_RFPforProjectWork_VendorSelection> tblVM_RFPforProjectWork_VendorSelection { get; set; }
        public virtual DbSet<tblVM_RFPforServiceAssets> tblVM_RFPforServiceAssets { get; set; }
        public virtual DbSet<tblVM_TaxMaster> tblVM_TaxMaster { get; set; }
        public virtual DbSet<tblVM_VComp_VendorSelection> tblVM_VComp_VendorSelection { get; set; }
        public virtual DbSet<tblVM_VendorComparison> tblVM_VendorComparison { get; set; }
        public virtual DbSet<tblVM_VendorSelectionFoRFP> tblVM_VendorSelectionFoRFP { get; set; }
        public virtual DbSet<tblVM_VendorSelectionForRFP_PartsComponent> tblVM_VendorSelectionForRFP_PartsComponent { get; set; }
        public virtual DbSet<tblVMRequestForPurchase> tblVMRequestForPurchases { get; set; }
        public virtual DbSet<tblVMSupplierPart> tblVMSupplierParts { get; set; }
        public virtual DbSet<tblWeatherData> tblWeatherDatas { get; set; }
        public virtual DbSet<tblWeeklyLogger> tblWeeklyLoggers { get; set; }
        public virtual DbSet<tblWorkForce> tblWorkForces { get; set; }
        public virtual DbSet<tblWorkForceToMaintenanceTeamMapping> tblWorkForceToMaintenanceTeamMappings { get; set; }
        public virtual DbSet<tblWorkOrderMaintenanceTask> tblWorkOrderMaintenanceTasks { get; set; }
        public virtual DbSet<tblWorkOrderResource> tblWorkOrderResources { get; set; }
        public virtual DbSet<tblWorkOrder> tblWorkOrders { get; set; }
        public virtual DbSet<tblXmlForBookedRoom> tblXmlForBookedRooms { get; set; }
        public virtual DbSet<testTable> testTables { get; set; }
        public virtual DbSet<Unit_type> Unit_type { get; set; }
        public virtual DbSet<Admin_Features_Activation> Admin_Features_Activation { get; set; }
        public virtual DbSet<BuildingImage> BuildingImages { get; set; }
        public virtual DbSet<LogoImage> LogoImages { get; set; }
        public virtual DbSet<tblLanguage> tblLanguages { get; set; }
        public virtual DbSet<tblPointSlouse> tblPointSlice { get; set; }
        public virtual DbSet<tblUnitOfMeasureCopySetup> tblUnitOfMeasureCopySetups { get; set; }
    }
}
