//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFIRM.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Point
    {
        public int PointID { get; set; }
        public string PointName { get; set; }
        public Nullable<int> PointSliceId { get; set; }
        public Nullable<int> LocationID { get; set; }
        public string Name { get; set; }
        public string DisplayNameShort { get; set; }
        public string UnitOfMeasureName { get; set; }
        public string Comment { get; set; }
        public Nullable<int> TimeZoneID { get; set; }
        public Nullable<int> DataSourceID { get; set; }
        public Nullable<int> PointDataTypeID { get; set; }
        public Nullable<int> PointTypeID { get; set; }
        public Nullable<bool> TimeStampIsLocalTime { get; set; }
        public string Source_Name { get; set; }
        public Nullable<int> DBFlag { get; set; }
    }
}
