//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFIRM.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sel_Point
    {
        public int Id { get; set; }
        public Nullable<int> PointId { get; set; }
        public Nullable<int> PointSliceId { get; set; }
        public Nullable<int> AssetId { get; set; }
        public Nullable<int> AlarmTypeId { get; set; }
        public Nullable<double> MinValue { get; set; }
        public Nullable<double> MaxValue { get; set; }
        public Nullable<bool> StatusCheck { get; set; }
        public Nullable<double> RuntimeLimit { get; set; }
        public Nullable<int> Severity { get; set; }
        public Nullable<bool> PMTrigger { get; set; }
        public Nullable<System.DateTime> StartTriggerDatetime { get; set; }
        public Nullable<int> SLAId { get; set; }
        public Nullable<bool> Email { get; set; }
        public Nullable<bool> SMS { get; set; }
        public Nullable<bool> GenerateServiceRequest { get; set; }
        public Nullable<int> OnValue { get; set; }
        public Nullable<int> OffValue { get; set; }
        public string PointValue { get; set; }
        public Nullable<int> ServiceTypeId { get; set; }
        public string PointType { get; set; }
        public Nullable<int> PointDataTypeId { get; set; }
        public Nullable<int> DeviceId { get; set; }
        public Nullable<int> PointComeFrom { get; set; }
    }
}
