//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFIRM.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_PointValue_Digital
    {
        public long nPointValue_DigitalId { get; set; }
        public Nullable<int> nPointId { get; set; }
        public Nullable<System.DateTime> dtPt_timeStamp { get; set; }
        public Nullable<short> nDigitalValue { get; set; }
    }
}
