//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFIRM.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ExceptionLogItems
    {
        public int nEventId { get; set; }
        public Nullable<System.DateTime> dtLogDateTime { get; set; }
        public string sSource { get; set; }
        public string sMessage { get; set; }
        public string sQueryString { get; set; }
        public string sTargetSite { get; set; }
        public string sStackTrace { get; set; }
        public string sServerName { get; set; }
        public string sRequestURL { get; set; }
        public string sUserAgent { get; set; }
        public string sUserIP { get; set; }
        public string sUserAuthentication { get; set; }
        public string sUserName { get; set; }
    }
}
