//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFIRM.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_newUpdatealarm
    {
        public int Id { get; set; }
        public int UpdatePointId { get; set; }
        public Nullable<int> IntelockPointId { get; set; }
        public string nDelayInSeconds { get; set; }
        public string TrggerType { get; set; }
        public Nullable<bool> Email { get; set; }
        public Nullable<bool> SMS { get; set; }
        public string alarmName { get; set; }
        public Nullable<bool> bIsActivate { get; set; }
    }
}
