//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFIRM.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_UnitOfMeasure
    {
        public int nUnitOfMeasureID { get; set; }
        public string sUnitOfMeasureName { get; set; }
        public string sMeasureType { get; set; }
        public string sDisplayNameShort { get; set; }
        public string sDisplayNameSingular { get; set; }
        public string sDisplayNamePlural { get; set; }
    }
}
