//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFIRM.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_TotalizationStatus
    {
        public int nTotalizationStatusId { get; set; }
        public Nullable<int> Id { get; set; }
        public Nullable<int> nObjectListId { get; set; }
        public Nullable<System.DateTime> dtLastDateTime { get; set; }
        public Nullable<int> tRunHoursTotal { get; set; }
        public Nullable<int> PointComeFrom { get; set; }
    
        public virtual tblAsset tblAsset { get; set; }
    }
}
