//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFIRM.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_RoomBookingMailStatus
    {
        public int Id { get; set; }
        public int RoomBookingId { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<System.DateTime> BookingEndDateTime { get; set; }
    }
}
