//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFIRM.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ObjectList
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_ObjectList()
        {
            this.tbl_TotalizationHistory = new HashSet<tbl_TotalizationHistory>();
        }
    
        public int nObjectListId { get; set; }
        public string sObjectName { get; set; }
        public Nullable<int> nObjectNumber { get; set; }
        public Nullable<int> nObjectType { get; set; }
        public string sIdentifier { get; set; }
        public string sMetasysName { get; set; }
        public Nullable<int> nUnit { get; set; }
        public Nullable<int> nDevicesId { get; set; }
        public Nullable<int> nLocId { get; set; }
        public string sStatus { get; set; }
    
        public virtual tbl_Devices tbl_Devices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_TotalizationHistory> tbl_TotalizationHistory { get; set; }
    }
}
