//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFIRM.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAccountSubHead
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblAccountSubHead()
        {
            this.tblPlanBadgets = new HashSet<tblPlanBadget>();
        }
    
        public int Id { get; set; }
        public string AccountSubHead { get; set; }
        public Nullable<int> ParentAccountId { get; set; }
        public Nullable<int> GLCodeId { get; set; }
    
        public virtual tblAccountHead tblAccountHead { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPlanBadget> tblPlanBadgets { get; set; }
    }
}
