//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFIRM.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAsset
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblAsset()
        {
            this.tbl_RunHrsOnOffTime = new HashSet<tbl_RunHrsOnOffTime>();
            this.tbl_TotalizationHistory = new HashSet<tbl_TotalizationHistory>();
            this.tbl_TotalizationLastFetchStatus = new HashSet<tbl_TotalizationLastFetchStatus>();
            this.tbl_TotalizationStatus = new HashSet<tbl_TotalizationStatus>();
            this.tblHelpDeskChangeRTAssets = new HashSet<tblHelpDeskChangeRTAsset>();
            this.tblHelpDeskRedirectAssets = new HashSet<tblHelpDeskRedirectAsset>();
            this.tblServiceReports = new HashSet<tblServiceReport>();
        }
    
        public int Id { get; set; }
        public Nullable<int> FacilityId { get; set; }
        public Nullable<int> BuildingId { get; set; }
        public Nullable<int> FloorId { get; set; }
        public Nullable<int> AreaId { get; set; }
        public Nullable<int> RoomId { get; set; }
        public string AssetName { get; set; }
        public Nullable<int> AssetGroupId { get; set; }
        public Nullable<int> AssetTypeId { get; set; }
        public Nullable<int> MakeId { get; set; }
        public Nullable<int> ModelId { get; set; }
        public string Serial { get; set; }
        public Nullable<double> ApproximatePurchaseCost { get; set; }
        public string CapacitySize { get; set; }
        public string BenchmarkValue { get; set; }
        public Nullable<double> MTBFHours { get; set; }
        public Nullable<System.DateTime> CommissioningDate { get; set; }
        public Nullable<System.DateTime> WarrantyDate { get; set; }
        public Nullable<bool> OwnedLeased { get; set; }
        public Nullable<System.DateTime> LeaseEndDate { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public Nullable<bool> Frequency { get; set; }
        public Nullable<bool> RunHours { get; set; }
        public Nullable<int> iState { get; set; }
        public string ifcId { get; set; }
        public string AssetDescription { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_RunHrsOnOffTime> tbl_RunHrsOnOffTime { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_TotalizationHistory> tbl_TotalizationHistory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_TotalizationLastFetchStatus> tbl_TotalizationLastFetchStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_TotalizationStatus> tbl_TotalizationStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblHelpDeskChangeRTAsset> tblHelpDeskChangeRTAssets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblHelpDeskRedirectAsset> tblHelpDeskRedirectAssets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblServiceReport> tblServiceReports { get; set; }
    }
}
