//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFIRM.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAccountBalance
    {
        public int Id { get; set; }
        public Nullable<int> OccupantId { get; set; }
        public Nullable<double> Balance { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> BalanceAddedBy { get; set; }
        public Nullable<int> PaymentMode { get; set; }
        public string BankName { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<double> Amount { get; set; }
        public string Number { get; set; }
    
        public virtual tblOccupant tblOccupant { get; set; }
    }
}
