//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFIRM.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAssetListReportTemplate
    {
        public int Id { get; set; }
        public string TemplateName { get; set; }
        public Nullable<System.DateTime> SavedDate { get; set; }
        public Nullable<int> FacilityId { get; set; }
        public Nullable<int> BuildingId { get; set; }
        public Nullable<int> FloorId { get; set; }
        public string AssetGroupStr { get; set; }
        public string AssetTypeStr { get; set; }
        public string MakeStr { get; set; }
        public string ModelStr { get; set; }
        public string LeasedOwnedStr { get; set; }
        public string CapacityGreatherthanEql { get; set; }
        public string CapacityLessThanEql { get; set; }
        public string MTBFFromHrs { get; set; }
        public string MTBFToHours { get; set; }
        public Nullable<System.DateTime> LeaseEndDateFrom { get; set; }
        public Nullable<System.DateTime> LeaseEndDateTo { get; set; }
        public Nullable<System.DateTime> ExpiryDateFrom { get; set; }
        public Nullable<System.DateTime> ExpiryDateTo { get; set; }
    }
}
