//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFIRM.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAssetComponentType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblAssetComponentType()
        {
            this.tblAssetComponents = new HashSet<tblAssetComponent>();
            this.tblVM_GRN_ComponentQuantity = new HashSet<tblVM_GRN_ComponentQuantity>();
            this.tblVM_RFPforComponents = new HashSet<tblVM_RFPforComponents>();
        }
    
        public int Id { get; set; }
        public string ComponentType { get; set; }
        public string ReorderLevel { get; set; }
        public string MinOrderQuantity { get; set; }
        public string MaximumLevel { get; set; }
        public Nullable<int> LeadTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAssetComponent> tblAssetComponents { get; set; }
        public virtual tblAssetComponentType tblAssetComponentType1 { get; set; }
        public virtual tblAssetComponentType tblAssetComponentType2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblVM_GRN_ComponentQuantity> tblVM_GRN_ComponentQuantity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblVM_RFPforComponents> tblVM_RFPforComponents { get; set; }
    }
}
