//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFIRM.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAssetType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblAssetType()
        {
            this.tbl_LogParameter = new HashSet<tbl_LogParameter>();
            this.tblComponentTypeAssets = new HashSet<tblComponentTypeAsset>();
            this.tblHelpDeskRedirectFlows = new HashSet<tblHelpDeskRedirectFlow>();
            this.tblKPIs = new HashSet<tblKPI>();
            this.tblMaintenanceActivityAssets = new HashSet<tblMaintenanceActivityAsset>();
            this.tblServiceReports = new HashSet<tblServiceReport>();
        }
    
        public int Id { get; set; }
        public Nullable<int> AssetGroupId { get; set; }
        public string AssetTypeName { get; set; }
        public string KPIValues { get; set; }
        public string KPIDesc { get; set; }
        public Nullable<bool> Frequency { get; set; }
        public Nullable<bool> Runhours { get; set; }
        public Nullable<bool> Fixed { get; set; }
        public Nullable<bool> Movable { get; set; }
        public Nullable<bool> IsCriticalEquipment { get; set; }
        public Nullable<bool> IsSpecialistContractor { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_LogParameter> tbl_LogParameter { get; set; }
        public virtual tblAssetGroup tblAssetGroup { get; set; }
        public virtual tblAssetType tblAssetType1 { get; set; }
        public virtual tblAssetType tblAssetType2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblComponentTypeAsset> tblComponentTypeAssets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblHelpDeskRedirectFlow> tblHelpDeskRedirectFlows { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblKPI> tblKPIs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblMaintenanceActivityAsset> tblMaintenanceActivityAssets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblServiceReport> tblServiceReports { get; set; }
    }
}
