//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFIRM.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblActualValueDigital
    {
        public int Id { get; set; }
        public int PointSliceID { get; set; }
        public System.DateTime UTCDateTime { get; set; }
        public short ActualValue { get; set; }
    }
}
