//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFIRM.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAnalogAlarm
    {
        public int Id { get; set; }
        public string AlarmName { get; set; }
        public string HighAlarm { get; set; }
        public Nullable<bool> Email { get; set; }
        public Nullable<bool> SMS { get; set; }
        public Nullable<int> PointId { get; set; }
        public string LowAlarm { get; set; }
        public string TriggerType { get; set; }
        public Nullable<bool> bISActivate { get; set; }
    }
}
