//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFIRM.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBookingRate
    {
        public int Id { get; set; }
        public Nullable<int> RoomId { get; set; }
        public Nullable<double> FromHour { get; set; }
        public Nullable<double> ToHour { get; set; }
        public Nullable<double> Rate { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
        public Nullable<double> RateOffBusinessHourRate { get; set; }
    
        public virtual tblRoom tblRoom { get; set; }
    }
}
