//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFIRM.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDocument
    {
        public int Id { get; set; }
        public Nullable<int> DocumentTypeId { get; set; }
        public string DocumentName { get; set; }
        public Nullable<int> UploadedBy { get; set; }
        public string HardCopyLoaction { get; set; }
        public Nullable<System.DateTime> ExpirationDate { get; set; }
        public Nullable<int> parentNode { get; set; }
        public Nullable<int> FacilityId { get; set; }
        public Nullable<int> BuildingId { get; set; }
        public Nullable<int> FloorId { get; set; }
        public Nullable<int> AssetId { get; set; }
        public Nullable<int> AssetGroupId { get; set; }
    
        public virtual tblDocumentType tblDocumentType { get; set; }
    }
}
