//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFIRM.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDailyLogger
    {
        public int Id { get; set; }
        public Nullable<int> HistoryId { get; set; }
        public Nullable<int> Unitid { get; set; }
        public Nullable<System.DateTime> LogDate { get; set; }
        public Nullable<double> DailyValue { get; set; }
    }
}
