//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFIRM.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDefineSoftservice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblDefineSoftservice()
        {
            this.tblTaskSoftservices = new HashSet<tblTaskSoftservice>();
        }
    
        public int Id { get; set; }
        public Nullable<int> FacilityId { get; set; }
        public Nullable<int> BuildingId { get; set; }
        public Nullable<int> FloorId { get; set; }
        public int AreaId { get; set; }
        public string SoftServiceName { get; set; }
        public string Description { get; set; }
        public Nullable<bool> Daily { get; set; }
        public Nullable<bool> Weekly { get; set; }
        public Nullable<bool> Monthly { get; set; }
        public Nullable<bool> FortNightly { get; set; }
        public Nullable<bool> HalfYearly { get; set; }
        public Nullable<bool> Yearly { get; set; }
        public Nullable<bool> Quarterly { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTaskSoftservice> tblTaskSoftservices { get; set; }
    }
}
