//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFIRM.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFBRoomDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblFBRoomDetail()
        {
            this.tblFBRoomDetailsWiseRates = new HashSet<tblFBRoomDetailsWiseRate>();
        }
    
        public int Id { get; set; }
        public Nullable<int> RoomId { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
    
        public virtual tblRoom tblRoom { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblFBRoomDetailsWiseRate> tblFBRoomDetailsWiseRates { get; set; }
    }
}
