//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFIRM.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFBAnnouncementMngt
    {
        public int Id { get; set; }
        public Nullable<int> FacilityId { get; set; }
        public Nullable<int> BuildingId { get; set; }
        public Nullable<int> FloorId { get; set; }
        public Nullable<int> RoomId { get; set; }
        public string BroadcastMessage { get; set; }
        public Nullable<System.DateTime> ValidTillDate { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
        public Nullable<int> LoginId { get; set; }
    
        public virtual tblBuilding tblBuilding { get; set; }
        public virtual tblFacility tblFacility { get; set; }
        public virtual tblFloor tblFloor { get; set; }
        public virtual tblRoom tblRoom { get; set; }
        public virtual tblUserLoginInfo tblUserLoginInfo { get; set; }
    }
}
