//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFIRM.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblForm
    {
        public int Id { get; set; }
        public string FormName { get; set; }
        public Nullable<int> MainModuleId { get; set; }
        public string ImageUrl { get; set; }
        public string PageUrl { get; set; }
        public Nullable<int> FormsSequenceNo { get; set; }
    
        public virtual tblMainModule tblMainModule { get; set; }
    }
}
