//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFIRM.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFBRoomDetailsWiseRate
    {
        public int Id { get; set; }
        public Nullable<int> RoomDetailsId { get; set; }
        public Nullable<int> MinimumHours { get; set; }
        public Nullable<int> BusinessHourRate { get; set; }
        public Nullable<int> OffBusinessHourRate { get; set; }
    
        public virtual tblFBRoomDetail tblFBRoomDetail { get; set; }
    }
}
