//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFIRM.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFBBusinessRule
    {
        public int Id { get; set; }
        public Nullable<bool> BusinessHoursFacility { get; set; }
        public Nullable<bool> OffBusinessHoursFacility { get; set; }
        public Nullable<bool> BusinessHoursRates { get; set; }
        public Nullable<bool> OffBusinessHoursRates { get; set; }
        public string IsIntegrationACS { get; set; }
        public string IsLightiningSystem { get; set; }
        public string IsApprovalProcess { get; set; }
        public Nullable<int> RoomCancelledHours { get; set; }
        public Nullable<int> ThresholdHours { get; set; }
        public string IsAnnounceMgnt { get; set; }
        public string BookingGaps { get; set; }
        public string AfterBookingNotifn { get; set; }
        public string EmailAfterBookingNotifn { get; set; }
        public string SMSAfterBookingNotifn { get; set; }
        public string BookingCancelNotifn { get; set; }
        public string EmailBookingCancelNotifn { get; set; }
        public string SMSBookingCancelNotifn { get; set; }
        public string AnnounceFromAdminNotifn { get; set; }
        public string EmailAnnounceFromAdminNotifn { get; set; }
        public string SMSAnnounceFromAdminNotifn { get; set; }
        public string ChangesScheduleNotifn { get; set; }
        public string EmailChangesScheduleNotifn { get; set; }
        public string SMSChangesScheduleNotifn { get; set; }
        public string OverrideBookingNotifn { get; set; }
        public string EmailOverrideBookingNotifn { get; set; }
        public string SMSOverrideBookingNotifn { get; set; }
        public Nullable<bool> RatesForUsers { get; set; }
        public Nullable<bool> RatesForTenants { get; set; }
        public Nullable<bool> isUserApproval { get; set; }
        public Nullable<bool> isTenantApproval { get; set; }
        public Nullable<int> FacilityId { get; set; }
        public Nullable<int> BuildingId { get; set; }
        public Nullable<int> FloorId { get; set; }
        public Nullable<int> RoomId { get; set; }
        public Nullable<bool> bAllowProgramSelection { get; set; }
        public Nullable<bool> bAllowCourseSelection { get; set; }
        public Nullable<bool> bAllowModuleSelection { get; set; }
    }
}
