//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFIRM.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblHelpDeskTemplate
    {
        public int Id { get; set; }
        public string TemplateName { get; set; }
        public Nullable<System.DateTime> SavedDate { get; set; }
        public Nullable<int> FacilityId { get; set; }
        public Nullable<int> BuildingId { get; set; }
        public Nullable<int> FloorId { get; set; }
        public string AssetTypeStr { get; set; }
        public string AssetStr { get; set; }
        public string ServiceRequestStr { get; set; }
        public string MaintenanceTypeStr { get; set; }
        public string SLAStr { get; set; }
        public string SeverityStr { get; set; }
        public string StatusStr { get; set; }
        public Nullable<System.DateTime> RequestFromDate { get; set; }
        public Nullable<System.DateTime> RequestToDate { get; set; }
        public Nullable<System.DateTime> ServiceReportFromDate { get; set; }
        public Nullable<System.DateTime> ServiceReportToDate { get; set; }
    }
}
