//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFIRM.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblHelpDeskChangeRTAsset
    {
        public int Id { get; set; }
        public Nullable<int> HelpDeskChangeRTDetailsId { get; set; }
        public Nullable<int> AssetId { get; set; }
    
        public virtual tblAsset tblAsset { get; set; }
        public virtual tblHelpDeskChangeRTDetail tblHelpDeskChangeRTDetail { get; set; }
    }
}
