//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFIRM.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblHelpDeskBusinessRule
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblHelpDeskBusinessRule()
        {
            this.tblApproverManagersLists = new HashSet<tblApproverManagersList>();
            this.tblRequestTypeApprovers = new HashSet<tblRequestTypeApprover>();
        }
    
        public int iBusinessRuleId { get; set; }
        public Nullable<bool> bSREmail { get; set; }
        public Nullable<bool> bSRSMS { get; set; }
        public Nullable<bool> bSRTenantEmail { get; set; }
        public Nullable<bool> bSRTenantSMS { get; set; }
        public Nullable<bool> bWOEmail { get; set; }
        public Nullable<bool> bWOSMS { get; set; }
        public Nullable<bool> bSOEmail { get; set; }
        public Nullable<bool> bSOSMS { get; set; }
        public Nullable<bool> bPPMWeekDays { get; set; }
        public Nullable<bool> bPPMWeekEnds { get; set; }
        public Nullable<bool> bPPMHolidays { get; set; }
        public Nullable<bool> bPPMEmail { get; set; }
        public Nullable<bool> bPPMSMS { get; set; }
        public string sSRAddEmail { get; set; }
        public string sSRAddTenantEmail { get; set; }
        public string sSRUpdateEmail { get; set; }
        public string sSRUpdateTenantEmail { get; set; }
        public string sSRDeleteEmail { get; set; }
        public string sSRDeleteTenantEmail { get; set; }
        public string sSRCloseEmail { get; set; }
        public string sSRCloseTenantEmail { get; set; }
        public string sSRAddSMS { get; set; }
        public string sSRAddTennatSMS { get; set; }
        public string sSRUpdateSMS { get; set; }
        public string sSRUpdateTenantSMS { get; set; }
        public string sSRDeleteSMS { get; set; }
        public string sSRDeleteTenantSMS { get; set; }
        public string sSRCloseSMS { get; set; }
        public string sSRCloseTenantSMS { get; set; }
        public string sWOAddEmail { get; set; }
        public string sWOUpdateEmail { get; set; }
        public string sWODeleteEmail { get; set; }
        public string sWOAddSMS { get; set; }
        public string sWOUpdateSMS { get; set; }
        public string sWODeleteSMS { get; set; }
        public string sSOAddEmail { get; set; }
        public string sSOUpdateEmail { get; set; }
        public string sSOAddSMS { get; set; }
        public string sSOUpdateSMS { get; set; }
        public string sSOUpdateTenantEmail { get; set; }
        public Nullable<System.TimeSpan> sPPMTime { get; set; }
        public string sPPMEmail { get; set; }
        public string sPPMSMS { get; set; }
        public Nullable<bool> bCustomerFeedbackInServiceReport { get; set; }
        public Nullable<int> iPPMUserId { get; set; }
        public Nullable<int> iEFIRMServiceStatusUserRoleId { get; set; }
        public Nullable<int> iRedirectTeamID { get; set; }
        public string sRedirectEmail { get; set; }
        public string sRedirectSMS { get; set; }
        public string sRedirectApprovalEmail { get; set; }
        public string sRedirectApprovalSMS { get; set; }
        public string sRedirectRejectEmail { get; set; }
        public string sRedirectRejectSMS { get; set; }
        public Nullable<bool> bRedirectEmail { get; set; }
        public Nullable<bool> bRedirectSMS { get; set; }
        public Nullable<bool> bRequestTypeEmail { get; set; }
        public Nullable<bool> bRequestTypeSMS { get; set; }
        public string sChangeRTRequestorEmail { get; set; }
        public string sChangeRTRequestorSMS { get; set; }
        public string sRTApprovalEmail { get; set; }
        public string sRTApprovalSMS { get; set; }
        public string sRTRejectEmail { get; set; }
        public string sRTRejectSMS { get; set; }
        public string sRTCancelledSREmail { get; set; }
        public string sRTCancelledSRSMS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblApproverManagersList> tblApproverManagersLists { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblRequestTypeApprover> tblRequestTypeApprovers { get; set; }
    }
}
