//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFIRM.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblIssueReturnItemsList
    {
        public int Id { get; set; }
        public Nullable<int> InventoryIssueReturnId { get; set; }
        public Nullable<int> PartCompId { get; set; }
        public string ItemName { get; set; }
        public string ItemUnit { get; set; }
        public Nullable<double> ReqQty { get; set; }
        public Nullable<double> StoreQuantity { get; set; }
        public string Serial { get; set; }
        public string Make { get; set; }
        public string Model { get; set; }
        public string Capacity { get; set; }
        public string Rating { get; set; }
        public Nullable<int> MaterialReqId { get; set; }
        public string IssueReturn { get; set; }
    
        public virtual tblInventoryIssueReturn tblInventoryIssueReturn { get; set; }
    }
}
