//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFIRM.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblKeyReturnedStatu
    {
        public int nReturnedStatusId { get; set; }
        public Nullable<int> nKeyId { get; set; }
        public Nullable<int> nPanelId { get; set; }
        public string sIsReturnedStatus { get; set; }
        public Nullable<int> nReturnedBy { get; set; }
    }
}
