//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFIRM.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblKeysIssueReturn
    {
        public int Id { get; set; }
        public string TransactionType { get; set; }
        public Nullable<int> FacilityId { get; set; }
        public Nullable<int> BuildingId { get; set; }
        public Nullable<int> FloorId { get; set; }
        public Nullable<int> AreaId { get; set; }
        public Nullable<int> RoomId { get; set; }
        public Nullable<int> KeyNameId { get; set; }
        public Nullable<int> KeyPanelId { get; set; }
        public string Description { get; set; }
        public Nullable<int> QuantityToBeIssued { get; set; }
        public Nullable<int> TotalAvailableQuanity { get; set; }
        public Nullable<int> IssuedTo { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
        public Nullable<System.DateTime> ExpectedReturnDate { get; set; }
        public Nullable<int> IssuedBy { get; set; }
        public Nullable<int> ReturnedBy { get; set; }
        public Nullable<System.DateTime> ReturnedDate { get; set; }
        public Nullable<int> KeyPanelIdForReturn { get; set; }
        public Nullable<int> ReturnedTo { get; set; }
        public string LoginTypeId { get; set; }
        public Nullable<int> ReturnedQuantity { get; set; }
    }
}
