//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFIRM.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLoggerHistory
    {
        public int HistoryId { get; set; }
        public Nullable<System.DateTime> DataLogDate { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> AssetId { get; set; }
        public string TemplateName { get; set; }
        public string Remark { get; set; }
        public Nullable<int> LoggerId { get; set; }
    }
}
