//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFIRM.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLicence
    {
        public int Id { get; set; }
        public string GeneratedKey { get; set; }
        public Nullable<bool> FacilitySetup { get; set; }
        public Nullable<bool> Assets { get; set; }
        public Nullable<bool> PartsAndInventory { get; set; }
        public Nullable<bool> Vendors { get; set; }
        public Nullable<bool> Workforce { get; set; }
        public Nullable<bool> Maintenance { get; set; }
        public Nullable<bool> HelpDesk { get; set; }
        public Nullable<bool> CostManagement { get; set; }
        public Nullable<bool> DocumentManagement { get; set; }
        public Nullable<bool> DataLogger { get; set; }
        public Nullable<bool> FacilityBooking { get; set; }
        public Nullable<bool> Dashboard { get; set; }
        public Nullable<bool> BIM { get; set; }
        public Nullable<bool> Reports { get; set; }
        public Nullable<bool> UserSetup { get; set; }
        public string ActivationKey { get; set; }
    }
}
