//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFIRM.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMRCourierServiceProvider
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblMRCourierServiceProvider()
        {
            this.tblMRMailroomInbounds = new HashSet<tblMRMailroomInbound>();
            this.tblMRMailroomOutbounds = new HashSet<tblMRMailroomOutbound>();
        }
    
        public int nCourierServiceProId { get; set; }
        public string sCompanyName { get; set; }
        public string sCourierCmpAddress { get; set; }
        public string sCourierCmpDescription { get; set; }
        public string sCourierCmpEmailId { get; set; }
        public string sCourierCmpAltEmailId { get; set; }
        public string sCourierCmpPhoneNo { get; set; }
        public string sCourierCmpAltPhoneNo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblMRMailroomInbound> tblMRMailroomInbounds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblMRMailroomOutbound> tblMRMailroomOutbounds { get; set; }
    }
}
