//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFIRM.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMRMailroomOutbound
    {
        public int nMailroomOutboundId { get; set; }
        public string sOutStatus { get; set; }
        public Nullable<System.DateTime> dtOutDate { get; set; }
        public string sOutTrackingNumber { get; set; }
        public Nullable<int> nOutCourierSerivceTypeId { get; set; }
        public Nullable<int> nOutModeOfDeliveryId { get; set; }
        public string sOutOrigin { get; set; }
        public string sOutDestination { get; set; }
        public string sOutItems { get; set; }
        public string sOutDescription { get; set; }
        public string sOutReceiverName { get; set; }
        public string sOutReceiverEmailId { get; set; }
        public string sOutReceiverCompanyName { get; set; }
        public string sOutReceiverContactNumber { get; set; }
        public Nullable<int> nOutSenderWorkforceId { get; set; }
        public string sOutSenderEmailId { get; set; }
        public string sOutSenderContactNumber { get; set; }
        public string sOutSenderDesignation { get; set; }
        public Nullable<System.DateTime> dtOutExpectedDeliveryDate { get; set; }
        public Nullable<double> fOutWeight { get; set; }
        public Nullable<double> fOutBoxDimension { get; set; }
    
        public virtual tblMRCourierServiceProvider tblMRCourierServiceProvider { get; set; }
        public virtual tblMRModeOfDelivery tblMRModeOfDelivery { get; set; }
        public virtual tblWorkForce tblWorkForce { get; set; }
    }
}
