//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFIRM.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMRModeOfDelivery
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblMRModeOfDelivery()
        {
            this.tblMRMailroomInbounds = new HashSet<tblMRMailroomInbound>();
            this.tblMRMailroomOutbounds = new HashSet<tblMRMailroomOutbound>();
        }
    
        public int nModeOfDeliveryId { get; set; }
        public string sModeOfDelivery { get; set; }
        public string sModeDescription { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblMRMailroomInbound> tblMRMailroomInbounds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblMRMailroomOutbound> tblMRMailroomOutbounds { get; set; }
    }
}
