//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFIRM.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblModule
    {
        public int nModuleId { get; set; }
        public Nullable<int> nProgramId { get; set; }
        public Nullable<int> nCourseId { get; set; }
        public string sModuleNumber { get; set; }
        public string sModuleName { get; set; }
        public string sModuleDescription { get; set; }
    
        public virtual tblCourse tblCourse { get; set; }
        public virtual tblProgram tblProgram { get; set; }
    }
}
