//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFIRM.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMaintenanceTask
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblMaintenanceTask()
        {
            this.tblMaintenanceTaskActivities = new HashSet<tblMaintenanceTaskActivity>();
            this.tblPPMTasks = new HashSet<tblPPMTask>();
        }
    
        public int Id { get; set; }
        public string TaskName { get; set; }
        public string Description { get; set; }
        public Nullable<bool> SuggestedFreqDaily { get; set; }
        public Nullable<bool> SuggestedFreqMonthly { get; set; }
        public Nullable<bool> SuggestedFreqQuaterly { get; set; }
        public Nullable<bool> SuggestedFreqHalfYearly { get; set; }
        public Nullable<bool> SuggestedFreqYearly { get; set; }
        public Nullable<double> RunHours { get; set; }
        public Nullable<double> NoOfHoursToComplete { get; set; }
        public Nullable<bool> ChkFrequncy { get; set; }
        public Nullable<bool> ChkRunHr { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblMaintenanceTaskActivity> tblMaintenanceTaskActivities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPPMTask> tblPPMTasks { get; set; }
    }
}
