//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFIRM.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMaintenanceActivite
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblMaintenanceActivite()
        {
            this.tblMaintenanceActivityAssets = new HashSet<tblMaintenanceActivityAsset>();
            this.tblMaintenanceTaskActivities = new HashSet<tblMaintenanceTaskActivity>();
        }
    
        public int Id { get; set; }
        public string ActivityName { get; set; }
        public string ActivityScope { get; set; }
        public string AssetMaintenance { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblMaintenanceActivityAsset> tblMaintenanceActivityAssets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblMaintenanceTaskActivity> tblMaintenanceTaskActivities { get; set; }
    }
}
