//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFIRM.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblNodeDoumentView
    {
        public int id { get; set; }
        public string NodeName { get; set; }
        public Nullable<int> ParentNode { get; set; }
        public Nullable<int> NodeType { get; set; }
        public Nullable<int> RelativeId { get; set; }
        public Nullable<int> FacilityId { get; set; }
        public Nullable<int> BuildingId { get; set; }
        public Nullable<int> FloorId { get; set; }
        public Nullable<int> AssetId { get; set; }
        public Nullable<int> AssetGroupId { get; set; }
    }
}
