//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFIRM.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblNotificationQueue
    {
        public int NotificationQueueId { get; set; }
        public Nullable<int> NotificationId { get; set; }
        public Nullable<System.DateTime> QueuedDate { get; set; }
        public string Frequency { get; set; }
        public string FormRequestType { get; set; }
        public string ToEmailID { get; set; }
        public string Subject { get; set; }
        public string Body { get; set; }
        public Nullable<bool> IsEmailSent { get; set; }
        public Nullable<int> FromUserId { get; set; }
        public Nullable<int> ToUserId { get; set; }
        public Nullable<bool> IsEmailRead { get; set; }
        public string ContactNumber { get; set; }
        public string MessageBody { get; set; }
        public Nullable<bool> IsSMSSent { get; set; }
        public Nullable<System.DateTime> EmailSentDateTime { get; set; }
        public Nullable<System.DateTime> SMSSentDateTime { get; set; }
        public Nullable<int> EmailSendAttempts { get; set; }
        public Nullable<int> SMSSendAttempts { get; set; }
    }
}
