//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFIRM.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOccupant
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblOccupant()
        {
            this.tblAccountBalances = new HashSet<tblAccountBalance>();
            this.tblFBInvoiceDetails = new HashSet<tblFBInvoiceDetail>();
            this.tblRoomBookingMasters = new HashSet<tblRoomBookingMaster>();
        }
    
        public int Id { get; set; }
        public Nullable<int> FacilityId { get; set; }
        public Nullable<int> BuildingId { get; set; }
        public Nullable<int> FloorId { get; set; }
        public Nullable<int> AreaId { get; set; }
        public Nullable<int> RoomId { get; set; }
        public string OccupantName { get; set; }
        public string ContactName { get; set; }
        public string ContactNumber { get; set; }
        public string ContactEmail { get; set; }
        public Nullable<int> cardHolderId { get; set; }
        public Nullable<bool> IsEVAccessOnly { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAccountBalance> tblAccountBalances { get; set; }
        public virtual tblFacility tblFacility { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblFBInvoiceDetail> tblFBInvoiceDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblRoomBookingMaster> tblRoomBookingMasters { get; set; }
    }
}
