//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFIRM.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPartsType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblPartsType()
        {
            this.tblParts = new HashSet<tblPart>();
            this.tblPartsAssets = new HashSet<tblPartsAsset>();
            this.tblVM_GRN_PartQuantity = new HashSet<tblVM_GRN_PartQuantity>();
            this.tblVM_RFPforParts = new HashSet<tblVM_RFPforParts>();
        }
    
        public int Id { get; set; }
        public string PartTypeName { get; set; }
        public string Tools { get; set; }
        public Nullable<int> UnitOfPartTypeId { get; set; }
        public Nullable<bool> Hazardous { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPart> tblParts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPartsAsset> tblPartsAssets { get; set; }
        public virtual tblUnitOfPartType tblUnitOfPartType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblVM_GRN_PartQuantity> tblVM_GRN_PartQuantity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblVM_RFPforParts> tblVM_RFPforParts { get; set; }
    }
}
