//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFIRM.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPPMSchedule
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblPPMSchedule()
        {
            this.tblPPMTasks = new HashSet<tblPPMTask>();
        }
    
        public int Id { get; set; }
        public Nullable<int> AssetId { get; set; }
        public Nullable<int> FacilityId { get; set; }
        public Nullable<int> BuildingId { get; set; }
        public Nullable<int> FloorId { get; set; }
        public Nullable<int> MonthVal { get; set; }
        public Nullable<int> YearVal { get; set; }
        public string Day1 { get; set; }
        public Nullable<int> FrequencyType1 { get; set; }
        public string Day2 { get; set; }
        public Nullable<int> FrequencyType2 { get; set; }
        public string Day3 { get; set; }
        public Nullable<int> FrequencyType3 { get; set; }
        public string Day4 { get; set; }
        public Nullable<int> FrequencyType4 { get; set; }
        public string Day5 { get; set; }
        public Nullable<int> FrequencyType5 { get; set; }
        public string Day6 { get; set; }
        public Nullable<int> FrequencyType6 { get; set; }
        public string Day7 { get; set; }
        public Nullable<int> FrequencyType7 { get; set; }
        public string Day8 { get; set; }
        public Nullable<int> FrequencyType8 { get; set; }
        public string Day9 { get; set; }
        public Nullable<int> FrequencyType9 { get; set; }
        public string Day10 { get; set; }
        public Nullable<int> FrequencyType10 { get; set; }
        public string Day11 { get; set; }
        public Nullable<int> FrequencyType11 { get; set; }
        public string Day12 { get; set; }
        public Nullable<int> FrequencyType12 { get; set; }
        public string Day13 { get; set; }
        public Nullable<int> FrequencyType13 { get; set; }
        public string Day14 { get; set; }
        public Nullable<int> FrequencyType14 { get; set; }
        public string Day15 { get; set; }
        public Nullable<int> FrequencyType15 { get; set; }
        public string Day16 { get; set; }
        public Nullable<int> FrequencyType16 { get; set; }
        public string Day17 { get; set; }
        public Nullable<int> FrequencyType17 { get; set; }
        public string Day18 { get; set; }
        public Nullable<int> FrequencyType18 { get; set; }
        public string Day19 { get; set; }
        public Nullable<int> FrequencyType19 { get; set; }
        public string Day20 { get; set; }
        public Nullable<int> FrequencyType20 { get; set; }
        public string Day21 { get; set; }
        public Nullable<int> FrequencyType21 { get; set; }
        public string Day22 { get; set; }
        public Nullable<int> FrequencyType22 { get; set; }
        public string Day23 { get; set; }
        public Nullable<int> FrequencyType23 { get; set; }
        public string Day24 { get; set; }
        public Nullable<int> FrequencyType24 { get; set; }
        public string Day25 { get; set; }
        public Nullable<int> FrequencyType25 { get; set; }
        public string Day26 { get; set; }
        public Nullable<int> FrequencyType26 { get; set; }
        public string Day27 { get; set; }
        public Nullable<int> FrequencyType27 { get; set; }
        public string Day28 { get; set; }
        public Nullable<int> FrequencyType28 { get; set; }
        public string Day29 { get; set; }
        public Nullable<int> FrequencyType29 { get; set; }
        public string Day30 { get; set; }
        public Nullable<int> FrequencyType30 { get; set; }
        public string Day31 { get; set; }
        public Nullable<int> FrequencyType31 { get; set; }
        public Nullable<int> MaintenanceTypeId { get; set; }
        public Nullable<int> PredictiveTypeId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPPMTask> tblPPMTasks { get; set; }
    }
}
