//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFIRM.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPrefixesMaster
    {
        public int Id { get; set; }
        public string RFPprefix { get; set; }
        public string PRFprefix { get; set; }
        public string POprefix { get; set; }
        public string GRNprefix { get; set; }
        public string Workorderprefix { get; set; }
        public string SerReqprefix { get; set; }
        public string SerRptprefix { get; set; }
        public string MRNprefix { get; set; }
        public string RoomBookingPrefix { get; set; }
    }
}
