//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFIRM.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPlusActual
    {
        public int Id { get; set; }
        public Nullable<int> FiscalYearId { get; set; }
        public Nullable<int> AccountHeadId { get; set; }
        public Nullable<int> AccountSubHeadId { get; set; }
        public Nullable<System.DateTime> SelectedDate { get; set; }
        public string Amount { get; set; }
        public string UserName { get; set; }
        public Nullable<System.DateTime> CurrentDate { get; set; }
        public string Description { get; set; }
    }
}
