//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFIRM.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPlanBadget
    {
        public int Id { get; set; }
        public Nullable<int> FiscalYearId { get; set; }
        public Nullable<int> AccountHeadId { get; set; }
        public Nullable<int> AccountSubHeadId { get; set; }
        public Nullable<double> January { get; set; }
        public Nullable<double> February { get; set; }
        public Nullable<double> March { get; set; }
        public Nullable<double> April { get; set; }
        public Nullable<double> May { get; set; }
        public Nullable<double> June { get; set; }
        public Nullable<double> July { get; set; }
        public Nullable<double> August { get; set; }
        public Nullable<double> September { get; set; }
        public Nullable<double> October { get; set; }
        public Nullable<double> November { get; set; }
        public Nullable<double> December { get; set; }
        public Nullable<double> TotalBadget { get; set; }
    
        public virtual tblAccountHead tblAccountHead { get; set; }
        public virtual tblAccountSubHead tblAccountSubHead { get; set; }
        public virtual tblFiscalYear tblFiscalYear { get; set; }
    }
}
