//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFIRM.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPortfolio
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string CorporateLogo { get; set; }
        public Nullable<int> FiscalStartMonth { get; set; }
        public Nullable<int> FiscalEndtMonth { get; set; }
        public Nullable<int> CurrencyId { get; set; }
        public string DateFormat { get; set; }
        public Nullable<int> AreaUnitId { get; set; }
        public string EntityName { get; set; }
        public string IfcId { get; set; }
        public Nullable<bool> DivStatus { get; set; }
    }
}
