//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFIRM.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPMSoftService
    {
        public int Id { get; set; }
        public int SoftServiceID { get; set; }
        public Nullable<System.DateTime> PlanDate { get; set; }
        public Nullable<int> FrequencyType { get; set; }
        public string ImagePath { get; set; }
    }
}
