//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFIRM.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPurchaseRequisition
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblPurchaseRequisition()
        {
            this.tblInventoryIssueReturns = new HashSet<tblInventoryIssueReturn>();
            this.tblPurchaseOrderLists = new HashSet<tblPurchaseOrderList>();
        }
    
        public int Id { get; set; }
        public Nullable<int> FacilityId { get; set; }
        public Nullable<int> BuildingId { get; set; }
        public Nullable<int> StoreId { get; set; }
        public string RequisitionNo { get; set; }
        public Nullable<System.DateTime> RequisitionDate { get; set; }
        public Nullable<int> WorkOrdersId { get; set; }
        public string LoginUserId { get; set; }
    
        public virtual tblBuilding tblBuilding { get; set; }
        public virtual tblFacility tblFacility { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblInventoryIssueReturn> tblInventoryIssueReturns { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPurchaseOrderList> tblPurchaseOrderLists { get; set; }
        public virtual tblPurchaseRequisition tblPurchaseRequisition1 { get; set; }
        public virtual tblPurchaseRequisition tblPurchaseRequisition2 { get; set; }
    }
}
