//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFIRM.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblResourceMakeModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblResourceMakeModel()
        {
            this.tblAttachedResourcesRoomWises = new HashSet<tblAttachedResourcesRoomWise>();
            this.tblFBAttachResourcesRoomWises = new HashSet<tblFBAttachResourcesRoomWise>();
        }
    
        public int Id { get; set; }
        public string ResourceName { get; set; }
        public string Make { get; set; }
        public string Model { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAttachedResourcesRoomWise> tblAttachedResourcesRoomWises { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblFBAttachResourcesRoomWise> tblFBAttachResourcesRoomWises { get; set; }
    }
}
