//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFIRM.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblReportShiftSchedule
    {
        public int Id { get; set; }
        public string TemplateName { get; set; }
        public Nullable<System.DateTime> SavedDate { get; set; }
        public Nullable<int> FacilityId { get; set; }
        public Nullable<int> BuildingId { get; set; }
        public string MaintenanceTeamStr { get; set; }
        public string DesignationStr { get; set; }
        public string ShiftStr { get; set; }
        public string LogMonth { get; set; }
        public string LogYear { get; set; }
    }
}
