//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFIRM.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblReportDataLogger
    {
        public int Id { get; set; }
        public string TemplateName { get; set; }
        public Nullable<System.DateTime> SavedDate { get; set; }
        public Nullable<int> FacilityId { get; set; }
        public Nullable<int> BuildingId { get; set; }
        public Nullable<int> LoggerTempId { get; set; }
        public Nullable<int> YearVal { get; set; }
        public Nullable<int> MonthVal { get; set; }
        public Nullable<int> WeekVal { get; set; }
        public Nullable<System.DateTime> LoggerDate { get; set; }
        public string AssetTypeStr { get; set; }
        public string AssetsStr { get; set; }
        public string UnitTypeStr { get; set; }
        public string UnitStr { get; set; }
        public string LoggerTemplate { get; set; }
    }
}
