//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFIRM.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblReortInventoryTemplate
    {
        public int Id { get; set; }
        public Nullable<int> FacilityId { get; set; }
        public Nullable<int> BuildingId { get; set; }
        public Nullable<int> FloorId { get; set; }
        public string TemplateName { get; set; }
        public Nullable<System.DateTime> SavedDate { get; set; }
        public string PartsTypeStr { get; set; }
        public string PartStr { get; set; }
        public string MakeStr { get; set; }
        public string ModelStr { get; set; }
        public string StatusStr { get; set; }
        public Nullable<System.DateTime> WarrantyEndFromDate { get; set; }
        public Nullable<System.DateTime> WarrantyEndToDate { get; set; }
    }
}
