//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFIRM.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRoom
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblRoom()
        {
            this.tblAttachedResourcesRoomWises = new HashSet<tblAttachedResourcesRoomWise>();
            this.tblBookingRates = new HashSet<tblBookingRate>();
            this.tblFBAnnouncementMngts = new HashSet<tblFBAnnouncementMngt>();
            this.tblFBAttachResourcesRoomWises = new HashSet<tblFBAttachResourcesRoomWise>();
            this.tblFBRoomDetails = new HashSet<tblFBRoomDetail>();
            this.tblKeys = new HashSet<tblKey>();
            this.tblRoomBookingMasters = new HashSet<tblRoomBookingMaster>();
        }
    
        public int Id { get; set; }
        public Nullable<int> FacilityId { get; set; }
        public Nullable<int> BuildingId { get; set; }
        public Nullable<int> FloorId { get; set; }
        public Nullable<int> AreaId { get; set; }
        public string RoomName { get; set; }
        public string RoomDescription { get; set; }
        public Nullable<int> RoomTypeId { get; set; }
        public Nullable<double> RoomSizeArea { get; set; }
        public Nullable<int> MaximumOccupancy { get; set; }
        public Nullable<bool> AvailableForBooking { get; set; }
        public string RoomImage { get; set; }
        public Nullable<bool> BMSControl { get; set; }
        public string ifcId { get; set; }
    
        public virtual tblArea tblArea { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAttachedResourcesRoomWise> tblAttachedResourcesRoomWises { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblBookingRate> tblBookingRates { get; set; }
        public virtual tblBuilding tblBuilding { get; set; }
        public virtual tblFacility tblFacility { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblFBAnnouncementMngt> tblFBAnnouncementMngts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblFBAttachResourcesRoomWise> tblFBAttachResourcesRoomWises { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblFBRoomDetail> tblFBRoomDetails { get; set; }
        public virtual tblFloor tblFloor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblKey> tblKeys { get; set; }
        public virtual tblRoomType tblRoomType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblRoomBookingMaster> tblRoomBookingMasters { get; set; }
    }
}
