//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFIRM.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStore
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblStore()
        {
            this.tblInventoryIssueReturns = new HashSet<tblInventoryIssueReturn>();
            this.tblInventoryParts = new HashSet<tblInventoryPart>();
        }
    
        public int Id { get; set; }
        public Nullable<int> FacilityNameId { get; set; }
        public Nullable<int> BuildingId { get; set; }
        public Nullable<int> RoomId { get; set; }
        public string StoreName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblInventoryIssueReturn> tblInventoryIssueReturns { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblInventoryPart> tblInventoryParts { get; set; }
    }
}
