//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFIRM.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblServiceRequest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblServiceRequest()
        {
            this.tblHelpDeskChangeRTDetails = new HashSet<tblHelpDeskChangeRTDetail>();
            this.tblWorkOrders = new HashSet<tblWorkOrder>();
        }
    
        public int Id { get; set; }
        public Nullable<int> FacilityId { get; set; }
        public string ServiceRequestNumber { get; set; }
        public Nullable<int> OccupantName { get; set; }
        public Nullable<int> BuildingId { get; set; }
        public Nullable<int> FloorId { get; set; }
        public Nullable<int> AreaId { get; set; }
        public string ContactNumber { get; set; }
        public string ContactEmail { get; set; }
        public string RequestType { get; set; }
        public Nullable<System.DateTime> RequestDate { get; set; }
        public Nullable<int> AssetTypeId { get; set; }
        public Nullable<int> AssetId { get; set; }
        public string RequestDescription { get; set; }
        public Nullable<int> ConfirmSLA { get; set; }
        public Nullable<int> Severity { get; set; }
        public string RequestMode { get; set; }
        public string StatusUpdatePreference { get; set; }
        public Nullable<int> AssignedTo { get; set; }
        public Nullable<System.DateTime> RequestClosureBy { get; set; }
        public string AcknowledgedBy { get; set; }
        public string Status { get; set; }
        public Nullable<int> ServiceTypeId { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public string ContactName { get; set; }
        public string WhoLogged { get; set; }
        public Nullable<System.DateTime> AcknowledgeDate { get; set; }
        public Nullable<System.DateTime> ClosingDate { get; set; }
        public Nullable<int> CategoryIdParentId { get; set; }
        public string SpecialInstructionForServiceRequest { get; set; }
        public Nullable<bool> IsThroughService { get; set; }
        public Nullable<int> RoomId { get; set; }
        public Nullable<int> ISeniorTechId { get; set; }
        public Nullable<int> AssetGroupId { get; set; }
        public Nullable<System.DateTime> RectificationDateTime { get; set; }
        public string ChangeRequestTypeStatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblHelpDeskChangeRTDetail> tblHelpDeskChangeRTDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblWorkOrder> tblWorkOrders { get; set; }
    }
}
