//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFIRM.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblShiftException
    {
        public int Id { get; set; }
        public Nullable<int> WorkForceId { get; set; }
        public Nullable<int> ShiftId { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
    
        public virtual tblShift tblShift { get; set; }
        public virtual tblWorkForce tblWorkForce { get; set; }
    }
}
