//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFIRM.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSLAEscalation
    {
        public int Id { get; set; }
        public Nullable<int> SLAId { get; set; }
        public Nullable<int> EscalationLevelId { get; set; }
        public Nullable<double> SeverityLevel1 { get; set; }
        public Nullable<double> SeverityLevel2 { get; set; }
        public Nullable<double> SeverityLevel3 { get; set; }
        public Nullable<int> EscalationToRolesId { get; set; }
        public Nullable<bool> EmailNotification { get; set; }
        public Nullable<bool> SMSNotification { get; set; }
    
        public virtual tblSLA tblSLA { get; set; }
        public virtual tblUserRole tblUserRole { get; set; }
    }
}
