//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFIRM.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSLA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblSLA()
        {
            this.tblSLAEscalations = new HashSet<tblSLAEscalation>();
            this.tblSLACategoryTypes = new HashSet<tblSLACategoryType>();
        }
    
        public int Id { get; set; }
        public string SLAType { get; set; }
        public Nullable<bool> IsDefault { get; set; }
        public Nullable<int> AcknowledgeThresholdMin { get; set; }
        public Nullable<int> AckEscalationLevel1RoleID { get; set; }
        public Nullable<int> AckEscalationLevel2RoleID { get; set; }
        public Nullable<int> AckEscalationLevel3RoleID { get; set; }
        public Nullable<bool> IsAckSMSNotificationSent { get; set; }
        public Nullable<bool> IsAckEmailNotificationSent { get; set; }
        public string RequestTypeSLA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSLAEscalation> tblSLAEscalations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSLACategoryType> tblSLACategoryTypes { get; set; }
    }
}
