//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFIRM.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblServiceReport
    {
        public int Id { get; set; }
        public Nullable<int> FacilityId { get; set; }
        public Nullable<int> WorkOrderId { get; set; }
        public string WORefNo { get; set; }
        public string ContractCoverage { get; set; }
        public Nullable<int> BuildingId { get; set; }
        public Nullable<int> FloorId { get; set; }
        public Nullable<int> AreaId { get; set; }
        public string ContactNo { get; set; }
        public string ContactEmail { get; set; }
        public string RequestType { get; set; }
        public Nullable<int> AssetTypeId { get; set; }
        public Nullable<int> AssetId { get; set; }
        public Nullable<int> ServiceStatus { get; set; }
        public Nullable<bool> CustomerSignOffreceived { get; set; }
        public string UploadSR { get; set; }
        public string ServiceReportNo { get; set; }
        public Nullable<System.DateTime> ReportDate { get; set; }
        public Nullable<bool> NotificationSend { get; set; }
        public Nullable<int> MaintenanceTaskId { get; set; }
        public string SignaturePath { get; set; }
        public Nullable<int> CategoryIdParentId { get; set; }
        public Nullable<int> CategoryTypeId { get; set; }
        public Nullable<bool> WorkHazardous { get; set; }
        public Nullable<bool> TestedForDefect { get; set; }
        public string Status { get; set; }
        public string Comments { get; set; }
        public Nullable<int> RoomId { get; set; }
        public Nullable<int> CustomerFeedbackId { get; set; }
        public Nullable<int> ReportSignedUserId { get; set; }
    
        public virtual tblAsset tblAsset { get; set; }
        public virtual tblAssetType tblAssetType { get; set; }
        public virtual tblBuilding tblBuilding { get; set; }
        public virtual tblCustomerFeedback tblCustomerFeedback { get; set; }
        public virtual tblFacility tblFacility { get; set; }
        public virtual tblFloor tblFloor { get; set; }
    }
}
