//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFIRM.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSmsStatu
    {
        public int SmsId { get; set; }
        public string ContactNumber { get; set; }
        public Nullable<System.DateTime> sentTime { get; set; }
        public string Replystatus { get; set; }
        public Nullable<System.DateTime> SCTimeStamp { get; set; }
        public string SendStatus { get; set; }
        public string MessageBody { get; set; }
        public string RequestNumber { get; set; }
        public string RequestTaskName { get; set; }
    }
}
