//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFIRM.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStockDetail
    {
        public int Id { get; set; }
        public string StoreName { get; set; }
        public string StockItem { get; set; }
        public string StockCode { get; set; }
        public string Catalog { get; set; }
        public string UnitPrice { get; set; }
        public string PhysicalQuantity { get; set; }
        public string ReorderThreshold { get; set; }
        public string Alarm { get; set; }
        public string Critical { get; set; }
        public string IsActive { get; set; }
    }
}
