//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFIRM.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTimeSheet
    {
        public int Id { get; set; }
        public Nullable<int> PersonId { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<int> WorkOrderId { get; set; }
        public string Task { get; set; }
        public string Monday { get; set; }
        public string Tuesday { get; set; }
        public string Wednesday { get; set; }
        public string Thursday { get; set; }
        public string Friday { get; set; }
        public string Saturday { get; set; }
        public string Sunday { get; set; }
        public Nullable<int> RptMgrId { get; set; }
        public string Status { get; set; }
    }
}
