//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFIRM.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUserRolesRights_Access
    {
        public int Id { get; set; }
        public string NodeName { get; set; }
        public Nullable<int> ParentId { get; set; }
        public Nullable<int> RelativeId { get; set; }
        public bool IsView { get; set; }
        public Nullable<bool> IsNoAccess { get; set; }
        public Nullable<int> UserRoleId { get; set; }
        public Nullable<bool> IsEdit { get; set; }
        public Nullable<bool> IsAdd { get; set; }
        public Nullable<bool> IsUpdate { get; set; }
        public Nullable<bool> IsDelete { get; set; }
    
        public virtual tblUserRole tblUserRole { get; set; }
    }
}
