//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFIRM.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUnitOfMeasureCopySetup
    {
        public int UnitOfMeasureID { get; set; }
        public string UnitOfMeasureName { get; set; }
        public string MeasureType { get; set; }
        public string DisplayNameShort { get; set; }
        public string DisplayNameSingular { get; set; }
        public string DisplayNamePlural { get; set; }
        public Nullable<int> LocationId { get; set; }
    }
}
