//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFIRM.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUserRole
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblUserRole()
        {
            this.tblSLAEscalations = new HashSet<tblSLAEscalation>();
            this.tblUserLoginInfoes = new HashSet<tblUserLoginInfo>();
            this.tblUserRolesRights_Access = new HashSet<tblUserRolesRights_Access>();
        }
    
        public int Id { get; set; }
        public string RoleName { get; set; }
        public string IsSuperAdmin { get; set; }
        public string AllowDigitalSignature { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSLAEscalation> tblSLAEscalations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblUserLoginInfo> tblUserLoginInfoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblUserRolesRights_Access> tblUserRolesRights_Access { get; set; }
    }
}
