//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFIRM.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUnit
    {
        public int UnitId { get; set; }
        public string UnitName { get; set; }
        public Nullable<int> UnitTypeId { get; set; }
    
        public virtual Unit_type Unit_type { get; set; }
    }
}
