//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFIRM.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblVM_RFPforServiceAssets
    {
        public int Id { get; set; }
        public Nullable<int> RFPforServiceId { get; set; }
        public Nullable<int> AssetGroupId { get; set; }
        public Nullable<int> AssetTypeId { get; set; }
        public Nullable<int> AssetsId { get; set; }
    
        public virtual tblVM_RFP_ForService tblVM_RFP_ForService { get; set; }
    }
}
