//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFIRM.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblVendorMasterGeneral
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblVendorMasterGeneral()
        {
            this.tblVM_VComp_VendorSelection = new HashSet<tblVM_VComp_VendorSelection>();
            this.tblVM_VendorSelectionFoRFP = new HashSet<tblVM_VendorSelectionFoRFP>();
            this.tblWorkForces = new HashSet<tblWorkForce>();
        }
    
        public int Id { get; set; }
        public string VendorName { get; set; }
        public string Address { get; set; }
        public string ContactPerson { get; set; }
        public string ContactEmail { get; set; }
        public string ContactPhNo { get; set; }
        public Nullable<bool> ServiceProvider { get; set; }
        public Nullable<bool> Supplier { get; set; }
        public Nullable<bool> OEM { get; set; }
        public string MsterAgreeFilePath { get; set; }
        public string VendorCode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblVM_VComp_VendorSelection> tblVM_VComp_VendorSelection { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblVM_VendorSelectionFoRFP> tblVM_VendorSelectionFoRFP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblWorkForce> tblWorkForces { get; set; }
    }
}
