//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFIRM.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblVM_RFPforPartsComponentMain
    {
        public int Id { get; set; }
        public string RFP_No { get; set; }
        public string RFPTitle { get; set; }
        public string Purpose { get; set; }
        public string WorkorderRefNo { get; set; }
        public Nullable<bool> IsSkipVendorComparison { get; set; }
        public string ApprovedBy { get; set; }
        public string DetailsOfPartsComp { get; set; }
        public Nullable<System.DateTime> ExpecDeliveryDateOfPartsComp { get; set; }
        public string DeliveryLocation { get; set; }
        public string UploadApprovedBy { get; set; }
    }
}
