//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFIRM.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblVM_RFPforParts
    {
        public int Id { get; set; }
        public Nullable<int> RFP_Id { get; set; }
        public Nullable<int> PartTypeId { get; set; }
        public Nullable<int> PartId { get; set; }
        public int Quantity { get; set; }
        public Nullable<double> PriceValue { get; set; }
    
        public virtual tblPart tblPart { get; set; }
        public virtual tblPartsType tblPartsType { get; set; }
    }
}
