//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFIRM.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblVM_GRN_PartQuantity
    {
        public int Id { get; set; }
        public Nullable<int> GRN_Id { get; set; }
        public Nullable<int> PartTypeId { get; set; }
        public Nullable<int> PartId { get; set; }
        public Nullable<int> OrderedQty { get; set; }
        public Nullable<int> PendingQty { get; set; }
        public Nullable<int> ReceivedQty { get; set; }
        public Nullable<int> AcceptedQty { get; set; }
        public Nullable<int> RejectedQty { get; set; }
        public Nullable<int> StoreId { get; set; }
    
        public virtual tblPart tblPart { get; set; }
        public virtual tblPartsType tblPartsType { get; set; }
        public virtual tblVM_GateReceiptNumber tblVM_GateReceiptNumber { get; set; }
    }
}
