//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFIRM.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblVM_RFP_ForService
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblVM_RFP_ForService()
        {
            this.tblVM_RFPforServiceAssets = new HashSet<tblVM_RFPforServiceAssets>();
        }
    
        public int Id { get; set; }
        public string RFP_No { get; set; }
        public string RFPtitle { get; set; }
        public string Purpose { get; set; }
        public string WorkorderRefNo { get; set; }
        public Nullable<bool> IsSkipVendorComparison { get; set; }
        public string ApprovedBy { get; set; }
        public string ScopeOfService { get; set; }
        public string Coverage { get; set; }
        public Nullable<System.DateTime> ServiceStartDate { get; set; }
        public Nullable<System.DateTime> ServiceEndDate { get; set; }
        public string UploadApprovedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblVM_RFPforServiceAssets> tblVM_RFPforServiceAssets { get; set; }
    }
}
