//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFIRM.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblVendorComparison
    {
        public int Id { get; set; }
        public Nullable<int> RFPTypeId { get; set; }
        public Nullable<int> RFPNo { get; set; }
        public Nullable<int> VendorId { get; set; }
        public Nullable<int> ValueId { get; set; }
        public Nullable<double> Value { get; set; }
        public Nullable<int> ValueId1 { get; set; }
    }
}
