//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFIRM.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblVM_PurchaseRequisitionForm
    {
        public int Id { get; set; }
        public string PRF_No { get; set; }
        public Nullable<int> RFP_Id { get; set; }
        public string PRFfilePath { get; set; }
        public Nullable<double> TotalValue { get; set; }
        public Nullable<int> AccountHeadId { get; set; }
        public Nullable<int> AccountSubheadId { get; set; }
        public Nullable<int> RFPTypeId { get; set; }
        public string RFPTitle { get; set; }
        public string Purpose { get; set; }
        public string ApprovedBy { get; set; }
    }
}
