//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFIRM.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblVM_POContract
    {
        public int Id { get; set; }
        public Nullable<int> RFPTypeId { get; set; }
        public Nullable<int> RFP_Id { get; set; }
        public string POContractNo { get; set; }
        public Nullable<System.DateTime> POContractStartDate { get; set; }
        public Nullable<System.DateTime> POContractEndDate { get; set; }
        public Nullable<double> POContractValue { get; set; }
        public string ApplicableTax { get; set; }
        public Nullable<double> TaxValue { get; set; }
        public string PaymentMode { get; set; }
        public string BankAccountNo { get; set; }
        public string SWIFTCode { get; set; }
        public string POContractFile { get; set; }
        public string PaymentTerm { get; set; }
        public string FreightTerm { get; set; }
        public string MiscCharge { get; set; }
        public string FreightCharge { get; set; }
        public string BillTo { get; set; }
        public string ShipTo { get; set; }
        public string PurchaseOrderNote { get; set; }
        public string CertificationAndApproval { get; set; }
        public Nullable<int> TaxMasterId_Tax1 { get; set; }
        public Nullable<double> ValueTax1 { get; set; }
        public Nullable<int> TaxMasterId_Tax2 { get; set; }
        public Nullable<double> ValueTax2 { get; set; }
        public Nullable<int> TaxMasterId_Tax3 { get; set; }
        public Nullable<double> ValueTax3 { get; set; }
        public Nullable<int> PRF_Id { get; set; }
    
        public virtual tblVM_POContract tblVM_POContract1 { get; set; }
        public virtual tblVM_POContract tblVM_POContract2 { get; set; }
        public virtual tblVM_TaxMaster tblVM_TaxMaster { get; set; }
        public virtual tblVM_TaxMaster tblVM_TaxMaster1 { get; set; }
        public virtual tblVM_TaxMaster tblVM_TaxMaster2 { get; set; }
    }
}
