//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFIRM.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblVM_RFPforProjectWork
    {
        public int Id { get; set; }
        public string ScopeOfWork { get; set; }
        public Nullable<System.DateTime> ExpectedStartDate { get; set; }
        public Nullable<double> Duration { get; set; }
        public string RfpNo { get; set; }
        public string RFPtitle { get; set; }
        public string Purpose { get; set; }
        public Nullable<bool> IsSkipVendorComparison { get; set; }
        public string ApprovedBy { get; set; }
        public string UploadApprovdBy { get; set; }
    }
}
