//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFIRM.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblVendorQualificationLevelName
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblVendorQualificationLevelName()
        {
            this.tblAssetTypeNQualificationLevels = new HashSet<tblAssetTypeNQualificationLevel>();
        }
    
        public int Id { get; set; }
        public string VendorQName { get; set; }
        public string Description { get; set; }
        public string Criteria { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAssetTypeNQualificationLevel> tblAssetTypeNQualificationLevels { get; set; }
        public virtual tblVendorQualificationLevelName tblVendorQualificationLevelName1 { get; set; }
        public virtual tblVendorQualificationLevelName tblVendorQualificationLevelName2 { get; set; }
    }
}
