//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFIRM.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblWorkOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblWorkOrder()
        {
            this.tblHelpDeskRedirectFlows = new HashSet<tblHelpDeskRedirectFlow>();
        }
    
        public int Id { get; set; }
        public Nullable<int> ServiceRequestId { get; set; }
        public Nullable<int> RequesterId { get; set; }
        public string Requesttype { get; set; }
        public Nullable<int> AssetId { get; set; }
        public Nullable<int> MaintenanceTaskId { get; set; }
        public Nullable<int> MaintenanceTypeId { get; set; }
        public Nullable<int> ApplicableSLAId { get; set; }
        public string Status { get; set; }
        public string WorkInstructions { get; set; }
        public string SafelyInstructions { get; set; }
        public string SpecialInstructions { get; set; }
        public string AdditionalInstructions { get; set; }
        public string WorkOrderRefNo { get; set; }
        public Nullable<System.DateTime> WorkOrderDate { get; set; }
        public Nullable<int> ServiceTypeId { get; set; }
        public Nullable<int> CategoryTypeId { get; set; }
        public Nullable<int> CategoryIdParentId { get; set; }
        public Nullable<bool> IsThroughService { get; set; }
        public string SDocumentName { get; set; }
        public Nullable<bool> IsRedirected { get; set; }
        public string RedirectStatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblHelpDeskRedirectFlow> tblHelpDeskRedirectFlows { get; set; }
        public virtual tblServiceRequest tblServiceRequest { get; set; }
    }
}
