//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFIRM.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblWorkOrderMaintenanceTask
    {
        public int Id { get; set; }
        public Nullable<int> ServiceRequestId { get; set; }
        public Nullable<int> WorkOrderId { get; set; }
        public Nullable<int> CategoryTypeId { get; set; }
        public string MaintenanceTask { get; set; }
        public string TaskDescription { get; set; }
        public string Remark { get; set; }
        public bool IsActivityChecked { get; set; }
        public Nullable<bool> IsActivityCheckedServiceReport { get; set; }
        public string CategoryType { get; set; }
        public Nullable<int> MaintenanceTaskId { get; set; }
        public Nullable<System.DateTime> TaskSheduledDate { get; set; }
    }
}
