//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFIRM.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblWorkForce
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblWorkForce()
        {
            this.tblHelpDeskChangeRTResources = new HashSet<tblHelpDeskChangeRTResource>();
            this.tblHelpDeskRedirectResources = new HashSet<tblHelpDeskRedirectResource>();
            this.tblMRMailroomInbounds = new HashSet<tblMRMailroomInbound>();
            this.tblMRMailroomOutbounds = new HashSet<tblMRMailroomOutbound>();
            this.tblShiftExceptions = new HashSet<tblShiftException>();
            this.tblShiftRosterings = new HashSet<tblShiftRostering>();
            this.tblWorkForce1 = new HashSet<tblWorkForce>();
            this.tblWorkForceToMaintenanceTeamMappings = new HashSet<tblWorkForceToMaintenanceTeamMapping>();
        }
    
        public int Id { get; set; }
        public string PersonName { get; set; }
        public Nullable<bool> IsEmployee { get; set; }
        public Nullable<int> DesignationId { get; set; }
        public Nullable<int> FacilityId { get; set; }
        public Nullable<int> VendorId { get; set; }
        public Nullable<int> ReportingMgr { get; set; }
        public string ContactEmail { get; set; }
        public string ContactNumber { get; set; }
        public string Status { get; set; }
    
        public virtual tblDesignation tblDesignation { get; set; }
        public virtual tblFacility tblFacility { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblHelpDeskChangeRTResource> tblHelpDeskChangeRTResources { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblHelpDeskRedirectResource> tblHelpDeskRedirectResources { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblMRMailroomInbound> tblMRMailroomInbounds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblMRMailroomOutbound> tblMRMailroomOutbounds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblShiftException> tblShiftExceptions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblShiftRostering> tblShiftRosterings { get; set; }
        public virtual tblVendorMasterGeneral tblVendorMasterGeneral { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblWorkForce> tblWorkForce1 { get; set; }
        public virtual tblWorkForce tblWorkForce2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblWorkForceToMaintenanceTeamMapping> tblWorkForceToMaintenanceTeamMappings { get; set; }
    }
}
