//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFIRM.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblWeatherData
    {
        public int nWeatherId { get; set; }
        public Nullable<System.DateTime> dteWeatherDate { get; set; }
        public string sTempreture { get; set; }
        public string sOutdoorRH { get; set; }
    }
}
