//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFIRM.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblXmlForBookedRoom
    {
        public string OperationType { get; set; }
        public int BookingId { get; set; }
        public Nullable<int> RoomId { get; set; }
        public Nullable<System.DateTime> BookingDate { get; set; }
        public Nullable<System.TimeSpan> BookingFromTime { get; set; }
        public Nullable<System.TimeSpan> BookingToTime { get; set; }
        public string Subject { get; set; }
        public string Agenda { get; set; }
        public Nullable<int> BookedForId { get; set; }
        public string ReceipentsEmailIds { get; set; }
        public string Rate { get; set; }
        public string BookingStatus { get; set; }
    }
}
